name = "coco-2017"

# Dataset Import
# Train split
[[DatasetImport]]
dataset_type = 'COCODetectionDataset'

[DatasetImport.importer_args]
dataset_dir = '/home/pep/Datasets/Coco2017/coco/'
data_path = 'images/train2017'
labels_path = 'annotations/instances_train2017.json'
label_types = 'detections' # 3 options ("detections", "segmentations", "keypoints")

# Extra args for train split
[DatasetImport.add_import_args]
tags = 'train'

# Val split
[[DatasetImport]]
dataset_type = 'COCODetectionDataset'

[DatasetImport.importer_args]
dataset_dir = '/home/pep/Datasets/Coco2017/coco/'
data_path = 'images/val2017'
labels_path = 'annotations/instances_val2017.json'
label_types = 'detections' # 3 options ("detections", "segmentations", "keypoints")

[DatasetImport.add_import_args]
tags = 'val'

# Export Dataset
# Train split
[[DatasetExport]]
dataset_type = 'YOLOv5Dataset'
match_tags = "train"

[DatasetExport.exporter_args]
export_dir = '/home/pep/Datasets/Coco2017/coco-yolo'
yaml_path = "dataset.yaml"
split = "train"
export_media = true
classes = 'default'

[DatasetExport.extra_export_args]

# Val split
[[DatasetExport]]
dataset_type = 'YOLOv5Dataset'
match_tags = "val"

[DatasetExport.exporter_args]
export_dir = '/home/pep/Datasets/Coco2017/coco-yolo'
yaml_path = "dataset.yaml"
split = "val"
export_media = true
classes = 'default'

[DatasetExport.extra_export_args]