name_dataset = "coco-2017"

# Train split
[[DatasetImport]]
dataset_dir = '/home/pep/Datasets/Coco2017/coco/'
dataset_type = 'COCODetectionDataset'
data_path = 'images/train2017'
labels_path = 'annotations/instances_train2017.json'
tags = 'train'

# Extra args for train split
[DatasetImport.extra_args]
max_samples = 200
label_types = 'detections'

# Val split
[[DatasetImport]]
dataset_dir = '/home/pep/Datasets/Coco2017/coco/'
dataset_type = 'COCODetectionDataset'
data_path = 'images/val2017'
labels_path = 'annotations/instances_val2017.json'
tags = 'val'

[DatasetImport.extra_args]
max_samples = 100
label_types = 'detections'

[[DatasetExport]]
export_dir = '/home/pep/Datasets/Coco2017/coco-yolo-test'
dataset_type = 'YOLOv5Dataset'
data_path = ''
labels_path = ''
export_media = true
overwrite = false
tags = "train"

[DatasetExport.extra_args]
split = 'train'
classes = 'default'

[[DatasetExport]]
export_dir = '/home/pep/Datasets/Coco2017/coco-yolo-test'
dataset_type = 'YOLOv5Dataset'
data_path = ''
labels_path = ''
export_media = true
overwrite = false
tags = "val"

[DatasetExport.extra_args]
split = 'val'
classes = 'default'